### PR TITLE
Search Submission

### PR DESCRIPTION
**Pull request by shahabgohar**
Search Page added.
dummy action method in action.js in search directory is wriiten for fetching data.
I have read the issue regarding best practices and will be implemented after this pull request
There is also refactoring done in the previous task.
Thank you !

### CODE REVIEW

**Comment by gbrian** [comment]
@shahabgohar , can you check those conflicts, everything else is fine! 👍

**Comment by shahabgohar** [comment]
@gbrian conflicts ressolved

**Comment by gbrian** [comment]
Fix responsive (screenshot is from a MacBook (witdh 1425px)
image

Footer should not be on top of results but at the end, so don't use <q-fotter> for this page

Mobile resulsts page:
image

please make that headers "dense":
 * Change user icon by a "burger" icon add user entre and navigation tabs there
 * recuce search input to fit between logo anf user icon

Sorry, didn't see this things beore.

**Comment by shahabgohar** [comment]
@gbrian duly noted

**Comment by shahabgohar** [comment]
@gbrian review changes
Screenshot_20210216-135631_Chrome

Screenshot_20210216-135638_Chrome

**Comment by gbrian** [comment]
Great work @shahabgohar ! 👏

**Pull request merged**
