### PR TITLE
co browsing page development

### PR DESCRIPTION
**Pull request by shahabgohar**
if there is any querry or update do tell me. I would be happy to help

### CODE REVIEW

**Comment by gbrian** [comment]
Hi @shahabgohar,
Can you please fix:
image

I'm missing more "componetization" page is crowded and difficult to maintain, we have to move elements to components as much as possible.

Room page must work on: desktop, ipad and as much as possible mobile. When it's portrait, users must be on top and no scroll.
Maybe is better to move all elements from layout to the page so it's easy to manage, what do you think?

I'm merging to start fixing some parts, I'll be posting when I have changes so you can take them.
Thanks

**Comment by shahabgohar** [comment]
@gbrian ok sure

**Comment by shahabgohar** [comment]
@gbrian made changes
tried to componentize as much as possible . if too much componentization occurs then their might be cohesion

**Comment by shahabgohar** [comment]
@gbrian  i have made new changes kindly check

**Comment by gbrian** [comment]
@shahabgohar still having scroll bars
The padding applied to: q-page-container is incorrect. BTW i think is worth it to move header to the `page` element as it will be chaging position for portrait/landscape. fine?

image

**Comment by shahabgohar** [comment]
@gbrian removed scrollbar

**Pull request merged**
